services:
  - type: web
    name: horizon-finanzas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
      - key: DATABASE_URL
